[shell]
#args = ['--login']
#working_directory ="C:\\Users\\" 
program = "cmd"
#
[cursor]
style = "Beam"

[font]
size = 14.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
startup_mode = "Maximized"
dynamic_padding = true
opacity = 1.0

[window.padding]
x = 6
y = 0

[mouse]
bindings = [
{ mouse = "Right", action = "Paste" }
]

[keyboard]
bindings = [
{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
{ key = "H", mods = "Control", action = "None" },
]

[selection]
save_to_clipboard = true



# Default colors
[colors.primary]
background = '#000000'
foreground = '#C0C7C8'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#800000'
green   = '#00A800'
yellow  = '#A85400'
blue    = '#000080'
magenta = '#A800A8'
cyan    = '#008080'
white   = '#A8A8A8'

# Bright colors
[colors.bright]
black   = '#545454'
red     = '#FC5454'
green   = '#54FC54'
yellow  = '#FCFC54'
blue    = '#5454FC'
magenta = '#FC54FC'
cyan    = '#54FCFC'
white   = '#FFFFFF'
[colors.cursor]
text = "CellBackground"


# [colors.normal]
# black = "#000000"
# red = "#800000"
# green = "#008000"
# yellow = "#ffff00"
# blue = "#000080"
# magenta = "#ff00ff"
# cyan = "#008080"
# white = "#ffffff"
#
# [colors.primary]
# background = '#181818'
# foreground = '#d8d8d8'
# # background = "#0a0c10"
# foreground = "#f0f3f6"

#

